import { createCrudResource, tagsField } from '../../helpers/resourceFactory';

const resourceModule = createCrudResource({
	resource: 'item',
	displayName: 'Item',
	apiObject: 'item',
	idField: 'itemid',
	getFilters: [
		{ name: 'hostids', displayName: 'Host IDs', description: 'Return items belonging to the given hosts' },
		{ name: 'groupids', displayName: 'Group IDs', description: 'Return items belonging to hosts in the given groups' },
		{ name: 'templateids', displayName: 'Template IDs', description: 'Return items belonging to the given templates' },
	],
	selects: [
		{ name: 'Hosts', value: 'selectHosts' },
		{ name: 'Preprocessing', value: 'selectPreprocessing' },
		{ name: 'Tags', value: 'selectTags' },
		{ name: 'Triggers', value: 'selectTriggers' },
	],
	jsonWriteKeys: ['tags', 'preprocessing'],
	writeFields: [
		{
			displayName: 'Host ID',
			name: 'hostid',
			type: 'string',
			default: '',
			description: 'ID of the host or template the item belongs to (required on create)',
		},
		{
			displayName: 'Name',
			name: 'name',
			type: 'string',
			default: '',
			description: 'Name of the item (required on create)',
		},
		{
			displayName: 'Key',
			name: 'key_',
			type: 'string',
			default: '',
			placeholder: 'system.cpu.load',
			description: 'Item key (required on create)',
		},
		{
			displayName: 'Type',
			name: 'type',
			type: 'options',
			default: 0,
			description: 'Item type',
			options: [
				{ name: 'Zabbix Agent', value: 0, description: 'Passive check — the server polls the agent (needs an Agent interface)' },
				{ name: 'Zabbix Trapper', value: 2, description: 'Values are pushed to Zabbix by zabbix_sender or History Push' },
				{ name: 'Simple Check', value: 3, description: 'Agentless checks like icmpping, net.tcp.service' },
				{ name: 'Zabbix Internal', value: 5, description: 'Metrics about Zabbix itself' },
				{ name: 'Zabbix Agent (Active)', value: 7, description: 'The agent polls the server for what to collect and pushes results' },
				{ name: 'External Check', value: 10, description: 'Runs a script from the externalscripts directory on the server' },
				{ name: 'Database Monitor', value: 11, description: 'Executes an SQL query via ODBC' },
				{ name: 'IPMI Agent', value: 12, description: 'Reads sensors from an IPMI board (needs an IPMI interface)' },
				{ name: 'SSH Agent', value: 13, description: 'Runs a command over SSH' },
				{ name: 'TELNET Agent', value: 14, description: 'Runs a command over Telnet' },
				{ name: 'Calculated', value: 15, description: 'Computes a formula over other items' },
				{ name: 'JMX Agent', value: 16, description: 'Reads Java JMX counters (needs a JMX interface)' },
				{ name: 'SNMP Trap', value: 17, description: 'Receives SNMP traps via snmptrapd' },
				{ name: 'Dependent Item', value: 18, description: 'Extracts its value from another (master) item' },
				{ name: 'HTTP Agent', value: 19, description: 'Polls an HTTP/REST endpoint' },
				{ name: 'SNMP Agent', value: 20, description: 'Polls an SNMP OID (needs an SNMP interface)' },
				{ name: 'Script', value: 21, description: 'Runs a JavaScript defined on the item' },
			],
		},
		{
			displayName: 'Value Type',
			name: 'value_type',
			type: 'options',
			default: 3,
			description: 'Type of value the item stores',
			options: [
				{ name: 'Numeric (Float)', value: 0, description: 'Decimal numbers, e.g. CPU load 1.23' },
				{ name: 'Character', value: 1, description: 'Short strings up to 255 characters' },
				{ name: 'Log', value: 2, description: 'Log lines with timestamp metadata' },
				{ name: 'Numeric (Unsigned)', value: 3, description: 'Whole numbers ≥ 0, e.g. bytes, counters' },
				{ name: 'Text', value: 4, description: 'Long text values' },
			],
		},
		{
			displayName: 'Update Interval',
			name: 'delay',
			type: 'string',
			default: '',
			placeholder: '30s',
			description: 'Update interval of the item (required for most item types)',
		},
		{
			displayName: 'Interface ID',
			name: 'interfaceid',
			type: 'string',
			default: '',
			description: 'ID of the host interface used by the item (required for some types)',
		},
		{
			displayName: 'Units',
			name: 'units',
			type: 'string',
			default: '',
			description: 'Value units',
		},
		{
			displayName: 'Status',
			name: 'status',
			type: 'options',
			default: 0,
			description: 'Whether the item is enabled',
			options: [
				{ name: 'Enabled', value: 0 },
				{ name: 'Disabled', value: 1 },
			],
		},
		tagsField('item'),
		{
			displayName: 'Preprocessing (JSON)',
			name: 'preprocessing',
			type: 'json',
			default: '',
			description: 'Array of preprocessing step objects',
		},
	],
});

export const description = resourceModule.description;
export const handlers = resourceModule.handlers;
