import { createGetOnlyResource } from '../../helpers/resourceFactory';

const resourceModule = createGetOnlyResource({
	resource: 'alert',
	displayName: 'Alert',
	apiObject: 'alert',
	getCommonOpts: { noNameSearch: true },
	idsParam: 'alertids',
	getFilters: [
		{ name: 'actionids', displayName: 'Action IDs', description: 'Return alerts generated by the given actions' },
		{ name: 'eventids', displayName: 'Event IDs', description: 'Return alerts generated by the given events' },
		{ name: 'hostids', displayName: 'Host IDs', description: 'Return alerts generated by the given hosts' },
		{ name: 'userids', displayName: 'User IDs', description: 'Return alerts sent to the given users' },
	],
});

export const description = resourceModule.description;
export const handlers = resourceModule.handlers;
